server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      teste: teste
    consumer:
      group-id: orchestrator-service-group
      auto-offset-reset: earliest

logging:
  level:
    org:
      apache:
        kafka: OFF